openapi: '3.0.0'
info:
  title: The Universal Transaction Protocol (UTP)
  description: transaction lifecycle specification
  version: 0.0.0
  contact:
    email: engineering@noshdelivery.io
security:
  - NodeAuth: []
paths:
  /merchant:
    $ref: './paths/merchant/GetMerchants.yaml'
  /merchant/{merchant_id}:
    $ref: './paths/merchant/GetMerchant.yaml'
  /catalog/{merchant_id}/search:
    $ref: './paths/merchant/GetMerchantCatalog.yaml'
  /item/{item_id}/modifiers:
    $ref: './paths/merchant/GetItemModifiers.yaml'
components:
  securitySchemes:
    $ref: './components/securitySchemes.yaml'
  schemas:
    $ref: './components/schemas.yaml'
  parameters: 
    $ref: './components/parameters.yaml'
  requestBodies: 
    $ref: './components/requestBodies.yaml'
  responses: 
    $ref: './components/responses.yaml'