openapi: '3.0.0'
info:
  title: The Universal Transaction Protocol (UTP)
  description: Transaction API specification for primary UTP commerce definitions
  version: 0.0.0
paths:
  /find_merchants:
    post:
      tags:
        - Seller Supporting Node (SSN)
      description: The BSN broadcasts the customer's request for merchants offering products or services
      requestBody:
        content:
          application/json:
            schema:
              $ref : './io/Search.yaml'
      responses:
        '200':
          description: A catalog of providers represented by the Seller Supporting Node (SSN)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Spacecraft'
        404:
          description: No data found for the provided value
          content:
            application/json:
              schema:
                $ref: './Error.yaml'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: './Error.yaml'
security:
  - ApiKey: []