openapi: '3.0.0'
info:
  title: The Universal Transaction Protocol (UTP)
  description: transaction lifecycle specification
  version: 0.0.0
security:
  - NodeAuth: []
paths:
  /cart:
    $ref: './checkout/api.yaml'
  /discover:
    $ref: './discovery/api.yaml'
components:
  securitySchemes:
    NodeAuth:
      type: apiKey
      in: header
      name: X-Stamp
      description: 'Signature of the request using BSN or SSN private key. <br/><br/>Format:<br/><br/><code>Authorization: Signature keyId="{node_id}|{unique_registry_id}|{algorithm}",algorithm="ed25519",created="1606970629",expires="1607030629",headers="(created) (expires) digest",signature="Base64url(signing string)"</code>'
  schemas:
    $ref: './components.yaml'