title: Menu
description: Defines a specific collection of items available for purchase
type: object
properties: 
    name: 
        type: string
        description: Provides context to the buyer about the menu and it's contents. (e.g. Lunch Menu)
    description:
        type: string
        description: Provides additional context to the buyer about the menu  and it's contents
    images:
        type: array
        items: 
            $ref: '../primitives/media/ImageFile.yaml'